# Generated by Django 5.2.3 on 2025-06-23 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=6)),
                ('credit', models.PositiveSmallIntegerField()),
                ('gpu_hours', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'Price Plan',
                'verbose_name_plural': 'Price Plans',
                'db_table': 'price_plans',
                'ordering': ['name'],
            },
        ),
    ]
