# Generated by Django 5.2.3 on 2025-06-23 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu', models.PositiveIntegerField()),
                ('memory', models.PositiveIntegerField()),
                ('gpu_count', models.PositiveIntegerField()),
                ('gpu_model', models.CharField(max_length=20)),
                ('credit', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'db_table': 'machines',
            },
        ),
    ]
